// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID                int64              `json:"id"`
	TmEventID         string             `json:"tm_event_id"`
	Name              string             `json:"name"`
	Url               string             `json:"url"`
	Venue             string             `json:"venue"`
	EventDate         pgtype.Timestamptz `json:"event_date"`
	LastMinPriceCents *int64             `json:"last_min_price_cents"`
	LastMaxPriceCents *int64             `json:"last_max_price_cents"`
	LastAvailability  *string            `json:"last_availability"`
	LastPolledAt      pgtype.Timestamptz `json:"last_polled_at"`
	NextPollAt        pgtype.Timestamptz `json:"next_poll_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID      int64              `json:"id"`
	WatchID int64              `json:"watch_id"`
	Channel string             `json:"channel"`
	SentAt  pgtype.Timestamptz `json:"sent_at"`
	Payload []byte             `json:"payload"`
}

type PriceSnapshot struct {
	ID                 int64              `json:"id"`
	EventID            int64              `json:"event_id"`
	MinPriceCents      *int64             `json:"min_price_cents"`
	MaxPriceCents      *int64             `json:"max_price_cents"`
	AvailabilityStatus *string            `json:"availability_status"`
	CheckedAt          pgtype.Timestamptz `json:"checked_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Watch struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	EventID        int64              `json:"event_id"`
	ConditionType  string             `json:"condition_type"`
	ThresholdCents *int64             `json:"threshold_cents"`
	Status         string             `json:"status"`
	LastEvaluation bool               `json:"last_evaluation"`
	LastNotifiedAt pgtype.Timestamptz `json:"last_notified_at"`
	PollIntervalS  int32              `json:"poll_interval_s"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
