// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWatchAlert = `-- name: ClaimWatchAlert :execrows
INSERT INTO watch_alerts (watch_id, kind)
VALUES ($1, $2)
ON CONFLICT (watch_id, kind) DO NOTHING
`

type ClaimWatchAlertParams struct {
	WatchID int64  `json:"watch_id"`
	Kind    string `json:"kind"`
}

// Exactly-once gate for one (watch, kind) alert. Returns 1 the first time and 0
// thereafter, so the caller sends the email only when it wins the insert. Doing
// this as a single statement avoids the read-then-write race a SELECT-then-INSERT
// would leave open.
func (q *Queries) ClaimWatchAlert(ctx context.Context, arg ClaimWatchAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimWatchAlert, arg.WatchID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeWatchesForEvent = `-- name: CloseWatchesForEvent :execrows
UPDATE watches SET status = 'paused' WHERE event_id = $1 AND status = 'active'
`

// Pause every active watch on an event (used when the event date has passed, so
// the scheduler stops spending API budget on it).
func (q *Queries) CloseWatchesForEvent(ctx context.Context, eventID int64) (int64, error) {
	result, err := q.db.Exec(ctx, closeWatchesForEvent, eventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countWatchesForUser = `-- name: CountWatchesForUser :one
SELECT count(*) FROM watches WHERE user_id = $1
`

func (q *Queries) CountWatchesForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWatchesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO auth_tokens (user_id, token_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, purpose, expires_at, used_at, created_at
`

type CreateAuthTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Purpose   string             `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// token_hash is the SHA-256 of the token we emailed; the raw value is never stored.
func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, createAuthToken,
		arg.UserID,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash) VALUES ($1, $2) RETURNING id, email, created_at, password_hash, email_verified_at, unsubscribed_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const createWatch = `-- name: CreateWatch :one
INSERT INTO watches (user_id, event_id, condition_type, poll_interval_s)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, event_id, condition_type, status, last_evaluation, last_notified_at, poll_interval_s, created_at
`

type CreateWatchParams struct {
	UserID        int64  `json:"user_id"`
	EventID       int64  `json:"event_id"`
	ConditionType string `json:"condition_type"`
	PollIntervalS int32  `json:"poll_interval_s"`
}

func (q *Queries) CreateWatch(ctx context.Context, arg CreateWatchParams) (Watch, error) {
	row := q.db.QueryRow(ctx, createWatch,
		arg.UserID,
		arg.EventID,
		arg.ConditionType,
		arg.PollIntervalS,
	)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.ConditionType,
		&i.Status,
		&i.LastEvaluation,
		&i.LastNotifiedAt,
		&i.PollIntervalS,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthTokensForUser = `-- name: DeleteAuthTokensForUser :exec
DELETE FROM auth_tokens WHERE user_id = $1 AND purpose = $2
`

type DeleteAuthTokensForUserParams struct {
	UserID  int64  `json:"user_id"`
	Purpose string `json:"purpose"`
}

// Invalidate outstanding tokens of one purpose: called when issuing a new one and
// after a successful redemption, so an old link in an inbox can't be replayed.
func (q *Queries) DeleteAuthTokensForUser(ctx context.Context, arg DeleteAuthTokensForUserParams) error {
	_, err := q.db.Exec(ctx, deleteAuthTokensForUser, arg.UserID, arg.Purpose)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

// Right to erasure. watches -> availability_snapshots/notifications cascade from the
// FKs in 0001_init, and auth_tokens cascades from 0003, so this removes every
// trace of the account in one statement.
func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWatch = `-- name: DeleteWatch :execrows
DELETE FROM watches WHERE id = $1 AND user_id = $2
`

type DeleteWatchParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteWatch(ctx context.Context, arg DeleteWatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWatch, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, tm_event_id, name, url, venue, event_date, last_availability, last_polled_at, next_poll_at, created_at, public_onsale_at, public_onsale_end_at, earliest_presale_at, earliest_presale_name, presale_count, onsale_tbd FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TmEventID,
		&i.Name,
		&i.Url,
		&i.Venue,
		&i.EventDate,
		&i.LastAvailability,
		&i.LastPolledAt,
		&i.NextPollAt,
		&i.CreatedAt,
		&i.PublicOnsaleAt,
		&i.PublicOnsaleEndAt,
		&i.EarliestPresaleAt,
		&i.EarliestPresaleName,
		&i.PresaleCount,
		&i.OnsaleTbd,
	)
	return i, err
}

const getEventByTMID = `-- name: GetEventByTMID :one
SELECT id, tm_event_id, name, url, venue, event_date, last_availability, last_polled_at, next_poll_at, created_at, public_onsale_at, public_onsale_end_at, earliest_presale_at, earliest_presale_name, presale_count, onsale_tbd FROM events WHERE tm_event_id = $1
`

func (q *Queries) GetEventByTMID(ctx context.Context, tmEventID string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByTMID, tmEventID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TmEventID,
		&i.Name,
		&i.Url,
		&i.Venue,
		&i.EventDate,
		&i.LastAvailability,
		&i.LastPolledAt,
		&i.NextPollAt,
		&i.CreatedAt,
		&i.PublicOnsaleAt,
		&i.PublicOnsaleEndAt,
		&i.EarliestPresaleAt,
		&i.EarliestPresaleName,
		&i.PresaleCount,
		&i.OnsaleTbd,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at, password_hash, email_verified_at, unsubscribed_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, created_at, password_hash, email_verified_at, unsubscribed_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const getValidAuthToken = `-- name: GetValidAuthToken :one
SELECT id, user_id, token_hash, purpose, expires_at, used_at, created_at FROM auth_tokens
WHERE token_hash = $1
  AND purpose    = $2
  AND used_at   IS NULL
  AND expires_at > now()
`

type GetValidAuthTokenParams struct {
	TokenHash string `json:"token_hash"`
	Purpose   string `json:"purpose"`
}

// Redeemable only while unused and unexpired, so lookup failure is indistinguishable
// between "wrong", "already used", and "expired" — nothing leaks to the caller.
func (q *Queries) GetValidAuthToken(ctx context.Context, arg GetValidAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, getValidAuthToken, arg.TokenHash, arg.Purpose)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWatch = `-- name: GetWatch :one
SELECT id, user_id, event_id, condition_type, status, last_evaluation, last_notified_at, poll_interval_s, created_at FROM watches WHERE id = $1 AND user_id = $2
`

type GetWatchParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetWatch(ctx context.Context, arg GetWatchParams) (Watch, error) {
	row := q.db.QueryRow(ctx, getWatch, arg.ID, arg.UserID)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.ConditionType,
		&i.Status,
		&i.LastEvaluation,
		&i.LastNotifiedAt,
		&i.PollIntervalS,
		&i.CreatedAt,
	)
	return i, err
}

const insertAvailabilitySnapshot = `-- name: InsertAvailabilitySnapshot :one
INSERT INTO availability_snapshots (event_id, availability_status)
VALUES ($1, $2)
RETURNING id, event_id, availability_status, checked_at
`

type InsertAvailabilitySnapshotParams struct {
	EventID            int64   `json:"event_id"`
	AvailabilityStatus *string `json:"availability_status"`
}

func (q *Queries) InsertAvailabilitySnapshot(ctx context.Context, arg InsertAvailabilitySnapshotParams) (AvailabilitySnapshot, error) {
	row := q.db.QueryRow(ctx, insertAvailabilitySnapshot, arg.EventID, arg.AvailabilityStatus)
	var i AvailabilitySnapshot
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.AvailabilityStatus,
		&i.CheckedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (watch_id, channel, payload)
VALUES ($1, $2, $3)
RETURNING id, watch_id, channel, sent_at, payload
`

type InsertNotificationParams struct {
	WatchID int64  `json:"watch_id"`
	Channel string `json:"channel"`
	Payload []byte `json:"payload"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification, arg.WatchID, arg.Channel, arg.Payload)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.WatchID,
		&i.Channel,
		&i.SentAt,
		&i.Payload,
	)
	return i, err
}

const listActiveWatchesForEvent = `-- name: ListActiveWatchesForEvent :many
SELECT w.id, w.user_id, w.event_id, w.condition_type, w.status, w.last_evaluation, w.last_notified_at, w.poll_interval_s, w.created_at, u.email AS user_email, u.email_verified_at, u.unsubscribed_at
FROM watches w
JOIN users u ON u.id = w.user_id
WHERE w.event_id = $1 AND w.status = 'active'
`

type ListActiveWatchesForEventRow struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	EventID         int64              `json:"event_id"`
	ConditionType   string             `json:"condition_type"`
	Status          string             `json:"status"`
	LastEvaluation  bool               `json:"last_evaluation"`
	LastNotifiedAt  pgtype.Timestamptz `json:"last_notified_at"`
	PollIntervalS   int32              `json:"poll_interval_s"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UserEmail       string             `json:"user_email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	UnsubscribedAt  pgtype.Timestamptz `json:"unsubscribed_at"`
}

// Includes the owner's email so the notifier can address the alert, plus the two
// states that decide whether we're allowed to mail them at all: verification
// (did they confirm the address?) and opt-out (did they unsubscribe?).
func (q *Queries) ListActiveWatchesForEvent(ctx context.Context, eventID int64) ([]ListActiveWatchesForEventRow, error) {
	rows, err := q.db.Query(ctx, listActiveWatchesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveWatchesForEventRow{}
	for rows.Next() {
		var i ListActiveWatchesForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.ConditionType,
			&i.Status,
			&i.LastEvaluation,
			&i.LastNotifiedAt,
			&i.PollIntervalS,
			&i.CreatedAt,
			&i.UserEmail,
			&i.EmailVerifiedAt,
			&i.UnsubscribedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueEvents = `-- name: ListDueEvents :many
SELECT e.id, e.tm_event_id, e.name, e.url, e.venue, e.event_date, e.last_availability, e.last_polled_at, e.next_poll_at, e.created_at, e.public_onsale_at, e.public_onsale_end_at, e.earliest_presale_at, e.earliest_presale_name, e.presale_count, e.onsale_tbd
FROM events e
WHERE e.next_poll_at <= now()
  AND EXISTS (SELECT 1 FROM watches w WHERE w.event_id = e.id AND w.status = 'active')
ORDER BY e.next_poll_at
LIMIT $1
`

// Events ready to poll that at least one active watch cares about.
func (q *Queries) ListDueEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listDueEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TmEventID,
			&i.Name,
			&i.Url,
			&i.Venue,
			&i.EventDate,
			&i.LastAvailability,
			&i.LastPolledAt,
			&i.NextPollAt,
			&i.CreatedAt,
			&i.PublicOnsaleAt,
			&i.PublicOnsaleEndAt,
			&i.EarliestPresaleAt,
			&i.EarliestPresaleName,
			&i.PresaleCount,
			&i.OnsaleTbd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiredAlertKinds = `-- name: ListFiredAlertKinds :many
SELECT kind FROM watch_alerts WHERE watch_id = $1
`

func (q *Queries) ListFiredAlertKinds(ctx context.Context, watchID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listFiredAlertKinds, watchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var kind string
		if err := rows.Scan(&kind); err != nil {
			return nil, err
		}
		items = append(items, kind)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT n.id, n.watch_id, n.channel, n.sent_at, n.payload FROM notifications n
JOIN watches w ON w.id = n.watch_id
WHERE w.user_id = $1
ORDER BY n.sent_at DESC
LIMIT $2
`

type ListNotificationsForUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.WatchID,
			&i.Channel,
			&i.SentAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsForEvent = `-- name: ListSnapshotsForEvent :many
SELECT id, event_id, availability_status, checked_at FROM availability_snapshots WHERE event_id = $1 ORDER BY checked_at ASC
`

func (q *Queries) ListSnapshotsForEvent(ctx context.Context, eventID int64) ([]AvailabilitySnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilitySnapshot{}
	for rows.Next() {
		var i AvailabilitySnapshot
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.AvailabilityStatus,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchesWithEvent = `-- name: ListWatchesWithEvent :many
SELECT w.id, w.user_id, w.event_id, w.condition_type, w.status, w.last_evaluation, w.last_notified_at, w.poll_interval_s, w.created_at,
       e.tm_event_id,
       e.name AS event_name,
       e.venue,
       e.url AS event_url,
       e.event_date,
       e.last_availability,
       e.last_polled_at,
       e.public_onsale_at,
       e.public_onsale_end_at,
       e.earliest_presale_at,
       e.earliest_presale_name,
       e.presale_count,
       e.onsale_tbd
FROM watches w
JOIN events e ON e.id = w.event_id
WHERE w.user_id = $1
ORDER BY w.created_at DESC
`

type ListWatchesWithEventRow struct {
	ID                  int64              `json:"id"`
	UserID              int64              `json:"user_id"`
	EventID             int64              `json:"event_id"`
	ConditionType       string             `json:"condition_type"`
	Status              string             `json:"status"`
	LastEvaluation      bool               `json:"last_evaluation"`
	LastNotifiedAt      pgtype.Timestamptz `json:"last_notified_at"`
	PollIntervalS       int32              `json:"poll_interval_s"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	TmEventID           string             `json:"tm_event_id"`
	EventName           string             `json:"event_name"`
	Venue               string             `json:"venue"`
	EventUrl            string             `json:"event_url"`
	EventDate           pgtype.Timestamptz `json:"event_date"`
	LastAvailability    *string            `json:"last_availability"`
	LastPolledAt        pgtype.Timestamptz `json:"last_polled_at"`
	PublicOnsaleAt      pgtype.Timestamptz `json:"public_onsale_at"`
	PublicOnsaleEndAt   pgtype.Timestamptz `json:"public_onsale_end_at"`
	EarliestPresaleAt   pgtype.Timestamptz `json:"earliest_presale_at"`
	EarliestPresaleName *string            `json:"earliest_presale_name"`
	PresaleCount        int32              `json:"presale_count"`
	OnsaleTbd           bool               `json:"onsale_tbd"`
}

func (q *Queries) ListWatchesWithEvent(ctx context.Context, userID int64) ([]ListWatchesWithEventRow, error) {
	rows, err := q.db.Query(ctx, listWatchesWithEvent, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWatchesWithEventRow{}
	for rows.Next() {
		var i ListWatchesWithEventRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.ConditionType,
			&i.Status,
			&i.LastEvaluation,
			&i.LastNotifiedAt,
			&i.PollIntervalS,
			&i.CreatedAt,
			&i.TmEventID,
			&i.EventName,
			&i.Venue,
			&i.EventUrl,
			&i.EventDate,
			&i.LastAvailability,
			&i.LastPolledAt,
			&i.PublicOnsaleAt,
			&i.PublicOnsaleEndAt,
			&i.EarliestPresaleAt,
			&i.EarliestPresaleName,
			&i.PresaleCount,
			&i.OnsaleTbd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuthTokenUsed = `-- name: MarkAuthTokenUsed :exec
UPDATE auth_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkAuthTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markAuthTokenUsed, id)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const markEventDue = `-- name: MarkEventDue :exec
UPDATE events SET next_poll_at = now() WHERE id = $1
`

// Make an event eligible for polling on the next scheduler tick. Called when a
// new watch is created so it is evaluated promptly instead of waiting for the
// event's next scheduled poll.
func (q *Queries) MarkEventDue(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markEventDue, id)
	return err
}

const markNotified = `-- name: MarkNotified :exec
UPDATE watches SET last_notified_at = now() WHERE id = $1
`

// Stamp when we last alerted. The watch stays 'active' (pure edge-trigger):
// it re-fires only on a new false->true transition, not while the condition stays true.
func (q *Queries) MarkNotified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotified, id)
	return err
}

const minPollIntervalForEvent = `-- name: MinPollIntervalForEvent :one
SELECT COALESCE(MIN(poll_interval_s), 300)::int AS interval_s
FROM watches
WHERE event_id = $1 AND status = 'active'
`

// Effective cadence for an event = the smallest interval any active watch asked for.
func (q *Queries) MinPollIntervalForEvent(ctx context.Context, eventID int64) (int32, error) {
	row := q.db.QueryRow(ctx, minPollIntervalForEvent, eventID)
	var interval_s int32
	err := row.Scan(&interval_s)
	return interval_s, err
}

const setLastEvaluation = `-- name: SetLastEvaluation :exec
UPDATE watches SET last_evaluation = $2 WHERE id = $1
`

type SetLastEvaluationParams struct {
	ID             int64 `json:"id"`
	LastEvaluation bool  `json:"last_evaluation"`
}

// Record the latest condition result (drives edge detection on the next poll).
func (q *Queries) SetLastEvaluation(ctx context.Context, arg SetLastEvaluationParams) error {
	_, err := q.db.Exec(ctx, setLastEvaluation, arg.ID, arg.LastEvaluation)
	return err
}

const setResubscribed = `-- name: SetResubscribed :exec
UPDATE users SET unsubscribed_at = NULL WHERE id = $1
`

func (q *Queries) SetResubscribed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setResubscribed, id)
	return err
}

const setUnsubscribed = `-- name: SetUnsubscribed :exec
UPDATE users SET unsubscribed_at = now() WHERE id = $1
`

// Idempotent on purpose: clicking an unsubscribe link twice must not error.
func (q *Queries) SetUnsubscribed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setUnsubscribed, id)
	return err
}

const updateEventLatest = `-- name: UpdateEventLatest :exec
UPDATE events
SET last_availability     = $2,
    public_onsale_at      = $3,
    public_onsale_end_at  = $4,
    earliest_presale_at   = $5,
    earliest_presale_name = $6,
    presale_count         = $7,
    onsale_tbd            = $8,
    last_polled_at        = now(),
    next_poll_at          = $9
WHERE id = $1
`

type UpdateEventLatestParams struct {
	ID                  int64              `json:"id"`
	LastAvailability    *string            `json:"last_availability"`
	PublicOnsaleAt      pgtype.Timestamptz `json:"public_onsale_at"`
	PublicOnsaleEndAt   pgtype.Timestamptz `json:"public_onsale_end_at"`
	EarliestPresaleAt   pgtype.Timestamptz `json:"earliest_presale_at"`
	EarliestPresaleName *string            `json:"earliest_presale_name"`
	PresaleCount        int32              `json:"presale_count"`
	OnsaleTbd           bool               `json:"onsale_tbd"`
	NextPollAt          pgtype.Timestamptz `json:"next_poll_at"`
}

func (q *Queries) UpdateEventLatest(ctx context.Context, arg UpdateEventLatestParams) error {
	_, err := q.db.Exec(ctx, updateEventLatest,
		arg.ID,
		arg.LastAvailability,
		arg.PublicOnsaleAt,
		arg.PublicOnsaleEndAt,
		arg.EarliestPresaleAt,
		arg.EarliestPresaleName,
		arg.PresaleCount,
		arg.OnsaleTbd,
		arg.NextPollAt,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateWatch = `-- name: UpdateWatch :one
UPDATE watches
SET status          = COALESCE($1, status),
    last_evaluation = CASE WHEN $2 THEN false ELSE last_evaluation END
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, event_id, condition_type, status, last_evaluation, last_notified_at, poll_interval_s, created_at
`

type UpdateWatchParams struct {
	Status          *string `json:"status"`
	ResetEvaluation bool    `json:"reset_evaluation"`
	ID              int64   `json:"id"`
	UserID          int64   `json:"user_id"`
}

// Partial update: a NULL status keeps the current value. reset_evaluation re-arms the
// watch so it can fire again on the next false->true edge.
func (q *Queries) UpdateWatch(ctx context.Context, arg UpdateWatchParams) (Watch, error) {
	row := q.db.QueryRow(ctx, updateWatch,
		arg.Status,
		arg.ResetEvaluation,
		arg.ID,
		arg.UserID,
	)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.ConditionType,
		&i.Status,
		&i.LastEvaluation,
		&i.LastNotifiedAt,
		&i.PollIntervalS,
		&i.CreatedAt,
	)
	return i, err
}

const upsertEventByTMID = `-- name: UpsertEventByTMID :one
INSERT INTO events (tm_event_id, name, url, venue, event_date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tm_event_id) DO UPDATE
    SET name       = EXCLUDED.name,
        url        = EXCLUDED.url,
        venue      = EXCLUDED.venue,
        event_date = EXCLUDED.event_date
RETURNING id, tm_event_id, name, url, venue, event_date, last_availability, last_polled_at, next_poll_at, created_at, public_onsale_at, public_onsale_end_at, earliest_presale_at, earliest_presale_name, presale_count, onsale_tbd
`

type UpsertEventByTMIDParams struct {
	TmEventID string             `json:"tm_event_id"`
	Name      string             `json:"name"`
	Url       string             `json:"url"`
	Venue     string             `json:"venue"`
	EventDate pgtype.Timestamptz `json:"event_date"`
}

func (q *Queries) UpsertEventByTMID(ctx context.Context, arg UpsertEventByTMIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, upsertEventByTMID,
		arg.TmEventID,
		arg.Name,
		arg.Url,
		arg.Venue,
		arg.EventDate,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TmEventID,
		&i.Name,
		&i.Url,
		&i.Venue,
		&i.EventDate,
		&i.LastAvailability,
		&i.LastPolledAt,
		&i.NextPollAt,
		&i.CreatedAt,
		&i.PublicOnsaleAt,
		&i.PublicOnsaleEndAt,
		&i.EarliestPresaleAt,
		&i.EarliestPresaleName,
		&i.PresaleCount,
		&i.OnsaleTbd,
	)
	return i, err
}
