// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWatch = `-- name: CreateWatch :one
INSERT INTO watches (user_id, event_id, condition_type, threshold_cents, poll_interval_s)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, event_id, condition_type, threshold_cents, status, last_evaluation, last_notified_at, poll_interval_s, created_at
`

type CreateWatchParams struct {
	UserID         int64  `json:"user_id"`
	EventID        int64  `json:"event_id"`
	ConditionType  string `json:"condition_type"`
	ThresholdCents *int64 `json:"threshold_cents"`
	PollIntervalS  int32  `json:"poll_interval_s"`
}

func (q *Queries) CreateWatch(ctx context.Context, arg CreateWatchParams) (Watch, error) {
	row := q.db.QueryRow(ctx, createWatch,
		arg.UserID,
		arg.EventID,
		arg.ConditionType,
		arg.ThresholdCents,
		arg.PollIntervalS,
	)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.ConditionType,
		&i.ThresholdCents,
		&i.Status,
		&i.LastEvaluation,
		&i.LastNotifiedAt,
		&i.PollIntervalS,
		&i.CreatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, tm_event_id, name, url, venue, event_date, last_min_price_cents, last_max_price_cents, last_availability, last_polled_at, next_poll_at, created_at FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TmEventID,
		&i.Name,
		&i.Url,
		&i.Venue,
		&i.EventDate,
		&i.LastMinPriceCents,
		&i.LastMaxPriceCents,
		&i.LastAvailability,
		&i.LastPolledAt,
		&i.NextPollAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByTMID = `-- name: GetEventByTMID :one
SELECT id, tm_event_id, name, url, venue, event_date, last_min_price_cents, last_max_price_cents, last_availability, last_polled_at, next_poll_at, created_at FROM events WHERE tm_event_id = $1
`

func (q *Queries) GetEventByTMID(ctx context.Context, tmEventID string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByTMID, tmEventID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TmEventID,
		&i.Name,
		&i.Url,
		&i.Venue,
		&i.EventDate,
		&i.LastMinPriceCents,
		&i.LastMaxPriceCents,
		&i.LastAvailability,
		&i.LastPolledAt,
		&i.NextPollAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const insertPriceSnapshot = `-- name: InsertPriceSnapshot :one
INSERT INTO price_snapshots (event_id, min_price_cents, max_price_cents, availability_status)
VALUES ($1, $2, $3, $4)
RETURNING id, event_id, min_price_cents, max_price_cents, availability_status, checked_at
`

type InsertPriceSnapshotParams struct {
	EventID            int64   `json:"event_id"`
	MinPriceCents      *int64  `json:"min_price_cents"`
	MaxPriceCents      *int64  `json:"max_price_cents"`
	AvailabilityStatus *string `json:"availability_status"`
}

func (q *Queries) InsertPriceSnapshot(ctx context.Context, arg InsertPriceSnapshotParams) (PriceSnapshot, error) {
	row := q.db.QueryRow(ctx, insertPriceSnapshot,
		arg.EventID,
		arg.MinPriceCents,
		arg.MaxPriceCents,
		arg.AvailabilityStatus,
	)
	var i PriceSnapshot
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.AvailabilityStatus,
		&i.CheckedAt,
	)
	return i, err
}

const listActiveWatchesForEvent = `-- name: ListActiveWatchesForEvent :many
SELECT id, user_id, event_id, condition_type, threshold_cents, status, last_evaluation, last_notified_at, poll_interval_s, created_at FROM watches WHERE event_id = $1 AND status = 'active'
`

func (q *Queries) ListActiveWatchesForEvent(ctx context.Context, eventID int64) ([]Watch, error) {
	rows, err := q.db.Query(ctx, listActiveWatchesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Watch{}
	for rows.Next() {
		var i Watch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.ConditionType,
			&i.ThresholdCents,
			&i.Status,
			&i.LastEvaluation,
			&i.LastNotifiedAt,
			&i.PollIntervalS,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueEvents = `-- name: ListDueEvents :many
SELECT e.id, e.tm_event_id, e.name, e.url, e.venue, e.event_date, e.last_min_price_cents, e.last_max_price_cents, e.last_availability, e.last_polled_at, e.next_poll_at, e.created_at
FROM events e
WHERE e.next_poll_at <= now()
  AND EXISTS (SELECT 1 FROM watches w WHERE w.event_id = e.id AND w.status = 'active')
ORDER BY e.next_poll_at
LIMIT $1
`

// Events ready to poll that at least one active watch cares about.
func (q *Queries) ListDueEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listDueEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TmEventID,
			&i.Name,
			&i.Url,
			&i.Venue,
			&i.EventDate,
			&i.LastMinPriceCents,
			&i.LastMaxPriceCents,
			&i.LastAvailability,
			&i.LastPolledAt,
			&i.NextPollAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchesWithEvent = `-- name: ListWatchesWithEvent :many
SELECT w.id, w.user_id, w.event_id, w.condition_type, w.threshold_cents, w.status, w.last_evaluation, w.last_notified_at, w.poll_interval_s, w.created_at,
       e.tm_event_id,
       e.name AS event_name,
       e.venue,
       e.event_date,
       e.last_min_price_cents,
       e.last_max_price_cents,
       e.last_availability,
       e.last_polled_at
FROM watches w
JOIN events e ON e.id = w.event_id
WHERE w.user_id = $1
ORDER BY w.created_at DESC
`

type ListWatchesWithEventRow struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	EventID           int64              `json:"event_id"`
	ConditionType     string             `json:"condition_type"`
	ThresholdCents    *int64             `json:"threshold_cents"`
	Status            string             `json:"status"`
	LastEvaluation    bool               `json:"last_evaluation"`
	LastNotifiedAt    pgtype.Timestamptz `json:"last_notified_at"`
	PollIntervalS     int32              `json:"poll_interval_s"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	TmEventID         string             `json:"tm_event_id"`
	EventName         string             `json:"event_name"`
	Venue             string             `json:"venue"`
	EventDate         pgtype.Timestamptz `json:"event_date"`
	LastMinPriceCents *int64             `json:"last_min_price_cents"`
	LastMaxPriceCents *int64             `json:"last_max_price_cents"`
	LastAvailability  *string            `json:"last_availability"`
	LastPolledAt      pgtype.Timestamptz `json:"last_polled_at"`
}

func (q *Queries) ListWatchesWithEvent(ctx context.Context, userID int64) ([]ListWatchesWithEventRow, error) {
	rows, err := q.db.Query(ctx, listWatchesWithEvent, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWatchesWithEventRow{}
	for rows.Next() {
		var i ListWatchesWithEventRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.ConditionType,
			&i.ThresholdCents,
			&i.Status,
			&i.LastEvaluation,
			&i.LastNotifiedAt,
			&i.PollIntervalS,
			&i.CreatedAt,
			&i.TmEventID,
			&i.EventName,
			&i.Venue,
			&i.EventDate,
			&i.LastMinPriceCents,
			&i.LastMaxPriceCents,
			&i.LastAvailability,
			&i.LastPolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const minPollIntervalForEvent = `-- name: MinPollIntervalForEvent :one
SELECT COALESCE(MIN(poll_interval_s), 300)::int AS interval_s
FROM watches
WHERE event_id = $1 AND status = 'active'
`

// Effective cadence for an event = the smallest interval any active watch asked for.
func (q *Queries) MinPollIntervalForEvent(ctx context.Context, eventID int64) (int32, error) {
	row := q.db.QueryRow(ctx, minPollIntervalForEvent, eventID)
	var interval_s int32
	err := row.Scan(&interval_s)
	return interval_s, err
}

const updateEventLatest = `-- name: UpdateEventLatest :exec
UPDATE events
SET last_min_price_cents = $2,
    last_max_price_cents = $3,
    last_availability    = $4,
    last_polled_at       = now(),
    next_poll_at         = $5
WHERE id = $1
`

type UpdateEventLatestParams struct {
	ID                int64              `json:"id"`
	LastMinPriceCents *int64             `json:"last_min_price_cents"`
	LastMaxPriceCents *int64             `json:"last_max_price_cents"`
	LastAvailability  *string            `json:"last_availability"`
	NextPollAt        pgtype.Timestamptz `json:"next_poll_at"`
}

func (q *Queries) UpdateEventLatest(ctx context.Context, arg UpdateEventLatestParams) error {
	_, err := q.db.Exec(ctx, updateEventLatest,
		arg.ID,
		arg.LastMinPriceCents,
		arg.LastMaxPriceCents,
		arg.LastAvailability,
		arg.NextPollAt,
	)
	return err
}

const upsertEventByTMID = `-- name: UpsertEventByTMID :one
INSERT INTO events (tm_event_id, name, url, venue, event_date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tm_event_id) DO UPDATE
    SET name       = EXCLUDED.name,
        url        = EXCLUDED.url,
        venue      = EXCLUDED.venue,
        event_date = EXCLUDED.event_date
RETURNING id, tm_event_id, name, url, venue, event_date, last_min_price_cents, last_max_price_cents, last_availability, last_polled_at, next_poll_at, created_at
`

type UpsertEventByTMIDParams struct {
	TmEventID string             `json:"tm_event_id"`
	Name      string             `json:"name"`
	Url       string             `json:"url"`
	Venue     string             `json:"venue"`
	EventDate pgtype.Timestamptz `json:"event_date"`
}

func (q *Queries) UpsertEventByTMID(ctx context.Context, arg UpsertEventByTMIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, upsertEventByTMID,
		arg.TmEventID,
		arg.Name,
		arg.Url,
		arg.Venue,
		arg.EventDate,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TmEventID,
		&i.Name,
		&i.Url,
		&i.Venue,
		&i.EventDate,
		&i.LastMinPriceCents,
		&i.LastMaxPriceCents,
		&i.LastAvailability,
		&i.LastPolledAt,
		&i.NextPollAt,
		&i.CreatedAt,
	)
	return i, err
}
